### ISSUE TITLE
Add "Configure the JooQ code generator" to documentation

### ISSUE THREAD

**Issue by paulhoule** [t9t/jooq-postgresql-json#7]
There is a link for this in the README.md but no actual instructions.

**Comment by t9t** [comment]
Good catch. In the past, this library had its own `Json` and `Jsonb` classes, and you would need to configure the jOOQ code generator to ensure that any `json` and `jsonb` fields in the database were mapped to these classes.

However since jOOQ release 3.12 it ships with its own `JSON` and `JSONB` classes, and `json` and `jsonb` fields are automatically mapped to those classes already. In version `1.0.0` I upgraded to jOOQ 3.12, threw out my own custom classes, and changed the library to use the native ones instead. However, I evidently forgot to remove it from the table of contents while updating the Readme. :)

I will remove the entry.
