### ISSUE TITLE
Question: Is it still relevant to use this lib with JOOQ 3.12 ?

### ISSUE THREAD

**Issue by fcamblor** [t9t/jooq-postgresql-json#9]
Hi,

Simple question as I'm considering using JOOQ on a new project where I'm going to use PostgreSQL's JSON types.

I'm totally new to JOOQ, but I stumbled upon https://github.com/jOOQ/jOOQ/issues/7242 and I'm wondering if support to PostgreSQL isn't "native" to JOOQ starting from 3.12.0.

=> Is there still an added value to use `jooq-postgresql-json` lib if I'm going to start using JOOQ 3.12+ ?

Thanks in advance :-)

**Comment by t9t** [comment]
Hi @fcamblor.

This module used to exist of two parts: 

1. A way to map PostgreSQL json(b) fields to objects rather than Strings; and
2. A collection of functions to use with jOOQ for PostgreSQL json(b) processing operators and functions: https://www.postgresql.org/docs/current/functions-json.html

Since jOOQ 3.12, the `JSON` and `JSONB` types were added to jOOQ itself and PostgreSQL json(b) fields are now automatically mapped to these types. That is https://github.com/jOOQ/jOOQ/issues/7242. That makes point number 1 obsolete. So since jOOQ 3.12 (and version 1.0.0 of this library) I have removed the custom json(b) classes and the mapper from this module.

However in jOOQ 3.12 there are yet no functions for json(b) processing. So point 2 is still valid, and that is what this library provides (through the `JsonDSL` and `JsonbDSL` classes).

So for instance, normally you would write something like this, to extract a JSON field:

```
dsl.select(DSL.field("{0}->>{1}", String.class, TABLE.JSONB_FIELD, "someKey")).from(TABLE);
```

Using this library, you would instead write:

```
dsl.select(JsonbDSL.fieldByKeyText(TABLE.JSONB_FIELD, "someKey")).from(TABLE);
```

So it may be a little more concise and perhaps readable and less duplication if you do this a lot.

I will rewrite the readme a little bit later to clarify this.

**Comment by fcamblor** [comment]
Thanks for the precisions, I think point 2 will definitely be useful for my needs :)

_(to add to the readability and concision, I guess there might be some typesafety as well ;-))_

**Comment by t9t** [comment]
Yes, all the methods in `JsonDSL` and `JsonbDSL` should match the types required by the actual PostgreSQL functions and what jOOQ expects.

I have updated the Readme with some code examples, clarified a bit what the library actually is for, and removed an obsolete section which was still referring to the custom code generation of previous versions.

Thanks for bringing this to my attention!
